Stop one system's brand rotation from preventing another
Twitter's brand rotation should be independent of the success of
Gravatar's. To do this, we tell them to continue on error, but that
would hide any errors, making it seem like the workflow succeeded when
it didn't completely. So we add a step to check the status of each
rotation and fail the workflow if either step failed.

diff --git a/.github/workflows/cron:rotate_branding.yml b/.github/workflows/cron:rotate_branding.yml
--- a/.github/workflows/cron:rotate_branding.yml
+++ b/.github/workflows/cron:rotate_branding.yml
@@ -29,7 +29,29 @@ jobs:
           bundle install --frozen --jobs 4 --retry 3 --without development test
 
       - name: Rotate Gravatar branding
+        id: gravatar
         run: rake brand_rotator:gravatar
+        continue-on-error: true
 
       - name: Rotate Twitter branding
+        id: twitter
         run: rake brand_rotator:twitter
+        continue-on-error: true
+
+      - name: Report failures
+        run: |
+          [[ "${{ steps.gravatar.outcome }}" == "success" ]]
+          GRAVATAR_SUCCESS=$?
+
+          [[ "${{ steps.twitter.outcome }}" == "success" ]]
+          TWITTER_SUCCESS=$?
+
+          [[ "$GRAVATAR_SUCCESS" == "0" ]] ||
+            echo "::error::Gravatar rotation did not succeed"
+          [[ "$TWITTER_SUCCESS" == "0" ]] ||
+            echo "::error::Twitter rotation did not succeed"
+
+          (
+            [[ "$GRAVATAR_SUCCESS" == "0" ]] &&
+            [[ "$TWITTER_SUCCESS" == "0" ]]
+          ) || exit 1
